import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { PublicFooter } from "@/components/public-footer";
import { PublicHeader } from "@/components/public-header";

const pages: Record<string,{title:string;eyebrow:string;copy:string;body:string[]}>={
  despre:{title:"O viață mai blândă nu începe cu mai multă presiune.",eyebrow:"Despre Starea Mea",copy:"Am creat un spațiu care respectă felul în care energia, atenția și emoțiile se schimbă de la o zi la alta.",body:["Starea Mea aduce împreună organizarea, focusul, journalingul și wellbeing-ul într-o experiență caldă, clară și fără rușine.","Nu diagnosticăm și nu înlocuim sprijinul unui profesionist calificat. Oferim instrumente de autocunoaștere și organizare pentru viața de zi cu zi."]},
  instrumente:{title:"Instrumente care nu te ceartă.",eyebrow:"Instrumente",copy:"De la check-in și Brain Dump la focus și jurnal — fiecare funcție începe cu energia pe care o ai.",body:["Planificatorul folosește «Reprogramează», nu «Întârziat». Timerul începe de la cinci minute. Jurnalul rămâne privat.","Recomandările sunt bazate pe reguli clare și pe preferințele tale. MVP-ul nu folosește inteligență artificială."]},
  resurse:{title:"Citește doar ce îți este util acum.",eyebrow:"Bibliotecă",copy:"Ghiduri și exerciții practice despre focus, organizare, emoții, somn și relația cu tine.",body:["Biblioteca este pregătită pentru articole, ghiduri, workbook-uri, audio și programe. Conținutul poate fi publicat din panoul de administrare."]},
  blog:{title:"Idei pentru zile reale.",eyebrow:"Jurnal editorial",copy:"Texte românești, clare și calde, fără promisiuni medicale sau productivitate toxică.",body:["Articolele vor apărea aici pe măsură ce sunt publicate și verificate editorial."]},
  contact:{title:"Suntem aici, cu răbdare.",eyebrow:"Contact",copy:"Pentru întrebări despre cont, plăți, confidențialitate sau colaborări.",body:["Scrie-ne la hello@stareamea.ro. Pentru urgențe medicale sau emoționale, contactează serviciile locale de urgență ori un profesionist calificat."]},
  confidentialitate:{title:"Datele tale sunt ale tale.",eyebrow:"Confidențialitate",copy:"Colectăm minimul necesar și separăm clar consimțământul de wellbeing de cel de marketing.",body:["Nu trimitem textul jurnalului, taskurile, stările zilnice sau răspunsurile sensibile către platforme de publicitate.","Poți solicita exportul datelor, șterge intrări individuale și iniția ștergerea contului din profil. Versiunea juridică finală trebuie revizuită înainte de lansare."]},
  termeni:{title:"Termeni simpli, fără surprize.",eyebrow:"Termeni și condiții",copy:"Starea Mea este un instrument de wellbeing, organizare și autocunoaștere, nu un serviciu medical.",body:["Abonamentele sunt procesate securizat prin Stripe și pot fi administrate din portalul clientului. Conținutul și funcțiile pot evolua, păstrând controlul utilizatoarei asupra datelor sale.","Acest text este o structură de produs și necesită revizuire juridică înainte de lansarea comercială."]}
};
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const page=pages[slug];return page?{title:page.eyebrow,description:page.copy}:{};}
export default async function PublicPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const page=pages[slug];if(!page)notFound();return <><PublicHeader/><main className="container-shell py-20 sm:py-28"><p className="eyebrow">{page.eyebrow}</p><h1 className="display mt-5 max-w-5xl text-6xl font-semibold leading-[.92] tracking-[-.04em] text-[var(--wine)] sm:text-8xl">{page.title}</h1><p className="mt-8 max-w-2xl text-xl leading-8 text-[var(--muted)]">{page.copy}</p><div className="mt-16 max-w-3xl border-t hairline pt-8">{page.body.map(p=><p key={p} className="mb-6 text-base leading-8 text-[var(--muted)]">{p}</p>)}</div></main><PublicFooter/></>}
