"use client";
/* eslint-disable react-hooks/immutability */
import { ArrowRight, GripVertical, Plus, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { Empty, ToolLayout } from "./planner";
type Bucket="inbox"|"today"|"week"|"later";type Item={id:string;body:string;bucket:Bucket};
const columns:[Bucket,string,string][]= [["inbox","Tot ce e în minte","Fără ordine"],["today","Azi","Doar ce contează"],["week","Săptămâna asta","Poate avea un loc"],["later","Poate aștepta","Nu dispare"]];
export function BrainDump(){const [items,setItems]=useState<Item[]>([]);const [body,setBody]=useState("");const [dragged,setDragged]=useState<string|null>(null);useEffect(()=>{void load()},[]);
 async function load(){const s=createClient();if(s){const {data:{user}}=await s.auth.getUser();if(user){const {data}=await s.from("brain_dump_items").select("id,body,bucket").order("sort_order");setItems((data as Item[])||[]);return;}}setItems(JSON.parse(localStorage.getItem("starea-mea-brain-dump")||"[]"));}
 function persist(next:Item[]){setItems(next);if(!createClient())localStorage.setItem("starea-mea-brain-dump",JSON.stringify(next));}
 async function add(){if(!body.trim())return;const s=createClient();if(s){const {data:{user}}=await s.auth.getUser();if(user){const {data}=await s.from("brain_dump_items").insert({user_id:user.id,body:body.trim(),bucket:"inbox"}).select().single();if(data)persist([...items,data as Item]);}}else persist([...items,{id:crypto.randomUUID(),body:body.trim(),bucket:"inbox"}]);setBody("");}
 async function move(id:string,bucket:Bucket){persist(items.map(x=>x.id===id?{...x,bucket}:x));const s=createClient();if(s)await s.from("brain_dump_items").update({bucket}).eq("id",id);}
 async function remove(id:string){persist(items.filter(x=>x.id!==id));const s=createClient();if(s)await s.from("brain_dump_items").delete().eq("id",id);}
 async function toTask(item:Item){const s=createClient();if(s){const {data:{user}}=await s.auth.getUser();if(user)await s.from("tasks").insert({user_id:user.id,title:item.body,estimated_minutes:15,energy:"medium",category:"personal",due_date:new Date().toISOString().slice(0,10)});}else{const tasks=JSON.parse(localStorage.getItem("starea-mea-tasks")||"[]");localStorage.setItem("starea-mea-tasks",JSON.stringify([...tasks,{id:crypto.randomUUID(),title:item.body,estimated_minutes:15,energy:"medium",category:"personal",priority:2,status:"todo",due_date:new Date().toISOString().slice(0,10)}]));}await move(item.id,"today");}
 return <ToolLayout eyebrow="Brain Dump" title="Scoate totul din mintea ta." intro="Scrie fără ordine și fără să decizi încă ce este important. Apoi mută fiecare lucru când ai spațiu."><section className="editorial-card paper-noise p-5 sm:p-8"><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Ce îți ocupă mintea acum?" className="min-h-36 w-full resize-none bg-transparent display text-2xl leading-relaxed text-[var(--wine)] outline-none placeholder:text-[var(--muted)]"/><div className="flex justify-end"><button onClick={add} className="button-primary"><Plus size={17}/>Pune pe hârtie</button></div></section><section className="grid gap-4 xl:grid-cols-4">{columns.map(([bucket,title,sub])=><div key={bucket} onDragOver={e=>e.preventDefault()} onDrop={()=>dragged&&move(dragged,bucket)} className="min-h-64 rounded-[18px] border border-dashed hairline bg-white/35 p-3"><div className="px-2 py-2"><h2 className="font-bold text-[var(--wine)]">{title}</h2><p className="text-xs text-[var(--muted)]">{sub}</p></div><div className="mt-2 grid gap-2">{items.filter(x=>x.bucket===bucket).map(item=><article draggable onDragStart={()=>setDragged(item.id)} key={item.id} className="rounded-2xl border hairline bg-white p-4 shadow-[0_10px_30px_rgba(86,55,62,.05)]"><div className="flex gap-2"><GripVertical size={16} className="mt-1 shrink-0 cursor-grab text-[var(--muted)]"/><p className="flex-1 text-sm leading-6 text-[var(--wine)]">{item.body}</p><button aria-label="Șterge" onClick={()=>remove(item.id)}><Trash2 size={15}/></button></div><div className="mt-3 flex justify-end">{bucket!=="today"&&<button onClick={()=>toTask(item)} className="inline-flex items-center gap-1 text-xs font-bold text-[var(--rose-dark)]">Transformă în task <ArrowRight size={13}/></button>}</div></article>)}{items.filter(x=>x.bucket===bucket).length===0&&<p className="px-2 py-5 text-xs leading-5 text-[var(--muted)]">Poți lăsa spațiul gol.</p>}</div></div>)}</section>{items.length===0&&<Empty title="Hârtia e goală și te așteaptă." copy="Primul gând poate fi oricât de mic."/>}</ToolLayout>}
