"use client";
import { ArrowLeft, Clock3, Flower2, Play } from "lucide-react";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { ToolLayout } from "./planner";
type Exercise={id:string;title:string;category:string;minutes:number;body:string};
const fallback:Exercise[]=[{id:"breath",title:"Respirația în patru colțuri",category:"Sunt copleșită",minutes:3,body:"Așază-te confortabil. Inspiră blând numărând până la patru. Fă o pauză scurtă. Expiră lent până la patru. Repetă fără să forțezi ritmul."},{id:"five",title:"Privește cinci lucruri",category:"Am prea multe gânduri",minutes:1,body:"Privește în jur și numește, în gând, cinci lucruri pe care le vezi. Nu trebuie să le descrii sau să le judeci."},{id:"pause",title:"Pauză senzorială",category:"Sunt suprastimulată",minutes:3,body:"Dacă poți, redu lumina și sunetul. Așază tălpile pe podea. Observă contactul lor cu solul. Nu trebuie să schimbi nimic altceva."}];
export function CalmLibrary(){const [items,setItems]=useState<Exercise[]>(fallback);const [selected,setSelected]=useState<Exercise|null>(null);useEffect(()=>{void (async()=>{const s=createClient();if(s){const {data}=await s.from("calm_exercises").select("id,title,category,minutes,body").eq("is_published",true).order("minutes");if(data?.length)setItems(data as Exercise[])}})()},[]);
 async function finish(){if(!selected)return;const s=createClient();if(s){const {data:{user}}=await s.auth.getUser();if(user)await s.from("calm_sessions").insert({user_id:user.id,exercise_id:selected.id,minutes:selected.minutes,completed:true})}setSelected(null)}
 if(selected)return <main className="grid min-h-[calc(100dvh-80px)] place-items-center p-5"><section className="editorial-card paper-noise w-full max-w-2xl p-8 sm:p-12"><button onClick={()=>setSelected(null)} className="inline-flex items-center gap-2 text-sm font-bold text-[var(--rose-dark)]"><ArrowLeft size={16}/>Înapoi</button><Flower2 className="mt-12 text-[var(--rose)]"/><p className="eyebrow mt-5">{selected.minutes} minute</p><h1 className="display mt-3 text-5xl font-semibold text-[var(--wine)]">{selected.title}</h1><p className="mt-8 text-lg leading-9 text-[var(--muted)]">{selected.body}</p><button onClick={finish} className="button-primary mt-10">Este suficient pentru acum</button></section></main>;
 const cats=[...new Set(items.map(x=>x.category))];return <ToolLayout eyebrow="Calm" title="Ce se întâmplă acum?" intro="Alege experiența cea mai apropiată. Exercițiile sunt pentru wellbeing și nu înlocuiesc sprijinul profesionist."><div className="grid gap-4 md:grid-cols-2">{cats.map(cat=><section key={cat} className="editorial-card p-6"><h2 className="display text-3xl font-semibold text-[var(--wine)]">{cat}</h2><div className="mt-4 grid gap-2">{items.filter(x=>x.category===cat).map(x=><button onClick={()=>setSelected(x)} key={x.id} className="flex items-center justify-between rounded-xl bg-[var(--blush)] p-4 text-left"><span><span className="block text-sm font-bold text-[var(--wine)]">{x.title}</span><span className="mt-1 flex items-center gap-1 text-xs text-[var(--muted)]"><Clock3 size={12}/>{x.minutes} min</span></span><Play size={17} className="text-[var(--rose)]"/></button>)}</div></section>)}</div></ToolLayout>}
