"use client";
import { ArrowLeft, Check, Pause, Play } from "lucide-react";
import { useState } from "react";
import { ToolLayout } from "./planner";
const templates:Record<string,{title:string;steps:string[]}[]>={
 "Curățenie":[{title:"Dormitor",steps:["Strânge doar hainele de pe podea.","Pune hainele murdare într-un singur loc.","Eliberează o singură suprafață.","Deschide geamul pentru un minut."]},{title:"Bucătărie",steps:["Pune cinci lucruri la loc.","Strânge vasele într-un singur loc.","Aruncă gunoiul.","Curăță o singură suprafață."]}],
 "Muncă":[{title:"Document dificil",steps:["Deschide documentul.","Scrie un titlu provizoriu.","Notează trei idei fără să le ordonezi.","Alege o singură idee și scrie două propoziții."]}],
 "Studiu":[{title:"Încep să învăț",steps:["Pune materialul în fața ta.","Alege doar o pagină.","Citește primul paragraf.","Notează un lucru pe care îl reții."]}],
 "Emailuri":[{title:"Inbox",steps:["Deschide inboxul.","Alege cel mai scurt email.","Scrie doar prima propoziție.","Trimite sau salvează ca draft."]}],
 "Organizare":[{title:"Hârtii",steps:["Adună hârtiile într-un singur loc.","Aruncă doar pliantele evidente.","Alege o hârtie care cere acțiune.","Notează acțiunea în planner."]}],
 "Gătit":[{title:"Ceva simplu",steps:["Bea puțină apă.","Alege o variantă cu maximum trei pași.","Scoate un singur ingredient.","Pregătește doar primul pas."]}],
 "Îngrijire personală":[{title:"Un gest pentru mine",steps:["Ridică-te sau schimbă poziția.","Mergi până la baie.","Alege un singur gest: apă, dinți sau față.","Oprește-te dacă este suficient."]}]
};
export function CantStart(){const [category,setCategory]=useState<string|null>(null);const [template,setTemplate]=useState<{title:string;steps:string[]}|null>(null);const [step,setStep]=useState(0);const [done,setDone]=useState(false);
 if(template){const current=template.steps[step];return <main className="grid min-h-[calc(100dvh-80px)] place-items-center p-5"><section className="editorial-card w-full max-w-2xl p-7 sm:p-12"><button onClick={()=>{setTemplate(null);setStep(0);setDone(false)}} className="inline-flex items-center gap-2 text-sm font-bold text-[var(--rose-dark)]"><ArrowLeft size={16}/>Alege altceva</button>{done?<div className="py-14 text-center"><span className="mx-auto grid size-14 place-items-center rounded-full bg-[var(--blush)] text-[var(--rose-dark)]"><Check/></span><p className="eyebrow mt-7">Este suficient</p><h1 className="display mt-3 text-6xl font-semibold text-[var(--wine)]">Ai început.</h1><p className="mt-4 text-[var(--muted)]">Nu trebuie să termini ca să conteze.</p></div>:<div className="py-10"><p className="eyebrow">{category} · {template.title} · pasul {step+1}</p><h1 className="display mt-6 text-5xl font-semibold leading-none text-[var(--wine)] sm:text-7xl">{current}</h1><p className="mt-6 text-[var(--muted)]">Atât. Nu ne gândim încă la pasul următor.</p><div className="mt-12 flex flex-wrap gap-3"><button onClick={()=>step<template.steps.length-1?setStep(step+1):setDone(true)} className="button-primary"><Play size={17}/>Mai facem unul</button><button onClick={()=>setDone(true)} className="button-secondary"><Pause size={17}/>Pauză</button><button onClick={()=>setDone(true)} className="button-secondary">Este suficient pentru azi</button></div></div>}</section></main>}
 return <ToolLayout eyebrow="Nu pot să încep" title="Începem cu ceva foarte mic." intro="Nu desfacem tot proiectul. Alegem un singur pas care cere cât mai puțină pornire."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.keys(templates).map(c=><button key={c} onClick={()=>setCategory(c)} className={`editorial-card min-h-28 p-5 text-left font-bold transition-transform hover:-translate-y-0.5 ${category===c?"border-[var(--rose)] bg-[var(--blush)]":""}`}>{c}</button>)}</div>{category&&<section className="editorial-card p-6"><p className="eyebrow">Alege un început</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{templates[category].map(t=><button key={t.title} onClick={()=>setTemplate(t)} className="rounded-2xl border hairline bg-white p-5 text-left"><span className="font-bold text-[var(--wine)]">{t.title}</span><span className="mt-2 block text-sm text-[var(--muted)]">Primul pas: {t.steps[0]}</span></button>)}</div></section>}</ToolLayout>}
