"use client";
/* eslint-disable react-hooks/exhaustive-deps */
import { Check, Pause, Play, RotateCcw, Square } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { ToolLayout } from "./planner";

export function FocusTimer(){const [duration,setDuration]=useState(25);const [seconds,setSeconds]=useState(25*60);const [task,setTask]=useState("");const [phase,setPhase]=useState<"setup"|"running"|"paused"|"done">("setup");const started=useRef<Date|null>(null);
 useEffect(()=>{if(phase!=="running")return;const timer=setInterval(()=>setSeconds(s=>{if(s<=1){clearInterval(timer);void complete(duration);setPhase("done");return 0}return s-1}),1000);return()=>clearInterval(timer)},[phase,duration]);
 function choose(n:number){setDuration(n);setSeconds(n*60)}
 async function complete(minutes:number){const s=createClient();const payload={task_label:task||"Focus blând",planned_minutes:duration,completed_minutes:minutes,outcome:"done",started_at:(started.current||new Date()).toISOString(),ended_at:new Date().toISOString()};if(s){const {data:{user}}=await s.auth.getUser();if(user)await s.from("focus_sessions").insert({...payload,user_id:user.id});}else{const old=JSON.parse(localStorage.getItem("starea-mea-focus")||"[]");localStorage.setItem("starea-mea-focus",JSON.stringify([...old,{...payload,id:crypto.randomUUID()}]));}}
 function start(){if(!task.trim())return;started.current=new Date();setPhase("running")}
 function reset(){setPhase("setup");setSeconds(duration*60);setTask("")}
 const clock=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
 if(phase==="running"||phase==="paused")return <main className="grid min-h-[calc(100dvh-80px)] place-items-center bg-[var(--wine)] p-6 text-white"><div className="text-center"><p className="eyebrow !text-[var(--rose-soft)]">Un singur lucru. Restul poate aștepta.</p><h1 className="display mt-6 max-w-2xl text-4xl font-semibold">{task}</h1><p aria-live="polite" className="display mt-10 text-[clamp(7rem,22vw,14rem)] font-semibold leading-none tabular-nums">{clock}</p><div className="mt-10 flex justify-center gap-3"><button onClick={()=>setPhase(phase==="running"?"paused":"running")} className="button-secondary !bg-white !text-[var(--wine)]">{phase==="running"?<Pause size={18}/>:<Play size={18}/>} {phase==="running"?"Pauză":"Continuă"}</button><button onClick={()=>{void complete(Math.max(1,duration-Math.ceil(seconds/60)));setPhase("done")}} className="button-secondary !border-white/20 !bg-transparent !text-white"><Square size={17}/>Încheie</button></div></div></main>;
 if(phase==="done")return <main className="grid min-h-[calc(100dvh-80px)] place-items-center p-6"><div className="editorial-card max-w-xl p-9 text-center"><span className="mx-auto grid size-14 place-items-center rounded-full bg-[var(--blush)] text-[var(--rose-dark)]"><Check/></span><p className="eyebrow mt-7">Ai fost aici pentru tine</p><h1 className="display mt-3 text-5xl font-semibold leading-none text-[var(--wine)]">Timpul tău contează.</h1><p className="mt-5 text-[var(--muted)]">Ai oferit atenție unui singur lucru, fără să ceri perfecțiune.</p><button onClick={reset} className="button-primary mt-8"><RotateCcw size={17}/>O nouă sesiune</button></div></main>;
 return <ToolLayout eyebrow="Focus" title="Un singur lucru." intro="Alege cât timp pare posibil acum. Cinci minute sunt o sesiune completă, nu doar un început."><section className="editorial-card p-6 sm:p-9"><label className="grid gap-3"><span className="text-sm font-bold text-[var(--wine)]">La ce lucrăm acum?</span><input value={task} onChange={e=>setTask(e.target.value)} placeholder="Un rezultat mic și clar…" className="min-h-14 rounded-xl border hairline bg-white px-4 text-lg outline-none focus:border-[var(--rose)]"/></label><div className="mt-8 flex flex-wrap gap-2">{[5,15,25,45,60].map(n=><button key={n} onClick={()=>choose(n)} className={`min-h-12 rounded-full px-5 font-bold ${duration===n?"bg-[var(--wine)] text-white":"bg-[var(--blush)] text-[var(--wine)]"}`}>{n} min</button>)}</div><button disabled={!task.trim()} onClick={start} className="button-primary mt-9 disabled:opacity-40"><Play size={18}/>Începe</button></section><section className="editorial-card bg-[var(--blush)] p-6"><p className="font-bold text-[var(--wine)]">Focus with me</p><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Scena rămâne simplă și liniștită. Sunetele ambientale pot fi activate după conectarea bibliotecii audio.</p></section></ToolLayout>}
