"use client";
/* eslint-disable react-hooks/immutability */
import { Heart, Plus, Search, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { Empty, ToolLayout } from "./planner";
type Entry={id:string;title:string|null;body:string;mode:"free"|"guided";is_favorite:boolean;entry_date:string;created_at:string};
const prompts=["Ce îți ocupă mintea acum?","Ce poți lăsa pentru mâine?","Ce te-a consumat astăzi?","Ce ai făcut mai bine decât crezi?","De ce ai nevoie acum?"];
export function Journal(){const [entries,setEntries]=useState<Entry[]>([]);const [mode,setMode]=useState<"free"|"guided">("free");const [prompt,setPrompt]=useState(prompts[0]);const [body,setBody]=useState("");const [query,setQuery]=useState("");useEffect(()=>{void load()},[]);
 async function load(){const s=createClient();if(s){const {data:{user}}=await s.auth.getUser();if(user){const {data}=await s.from("journal_entries").select("id,title,body,mode,is_favorite,entry_date,created_at").order("created_at",{ascending:false});setEntries((data as Entry[])||[]);return}}setEntries(JSON.parse(localStorage.getItem("starea-mea-journal")||"[]"))}
 function persist(next:Entry[]){setEntries(next);if(!createClient())localStorage.setItem("starea-mea-journal",JSON.stringify(next))}
 async function save(){if(!body.trim())return;const draft={title:mode==="guided"?prompt:null,body:body.trim(),mode,is_favorite:false,entry_date:new Date().toISOString().slice(0,10),created_at:new Date().toISOString()};const s=createClient();if(s){const {data:{user}}=await s.auth.getUser();if(user){const {data}=await s.from("journal_entries").insert({...draft,user_id:user.id}).select().single();if(data)persist([data as Entry,...entries])}}else persist([{...draft,id:crypto.randomUUID()},...entries]);setBody("")}
 async function favorite(e:Entry){persist(entries.map(x=>x.id===e.id?{...x,is_favorite:!x.is_favorite}:x));const s=createClient();if(s)await s.from("journal_entries").update({is_favorite:!e.is_favorite}).eq("id",e.id)}
 async function remove(id:string){persist(entries.filter(x=>x.id!==id));const s=createClient();if(s)await s.from("journal_entries").delete().eq("id",id)}
 const filtered=useMemo(()=>entries.filter(x=>`${x.title||""} ${x.body} ${x.entry_date}`.toLowerCase().includes(query.toLowerCase())),[entries,query]);
 return <ToolLayout eyebrow="Jurnalul meu" title="Un loc privat pentru ce este al tău." intro="Textul jurnalului nu este trimis în analytics sau către platforme publicitare."><section className="editorial-card paper-noise p-6 sm:p-9"><div className="flex gap-2">{[["free","Scriu liber"],["guided","Jurnal ghidat"]].map(([id,label])=><button key={id} onClick={()=>setMode(id as typeof mode)} className={`min-h-10 rounded-full px-4 text-sm font-bold ${mode===id?"bg-[var(--wine)] text-white":"bg-white text-[var(--muted)]"}`}>{label}</button>)}</div>{mode==="guided"&&<div className="mt-6 flex flex-wrap gap-2">{prompts.map(p=><button key={p} onClick={()=>setPrompt(p)} className={`rounded-full border px-3 py-2 text-xs ${prompt===p?"border-[var(--rose)] bg-[var(--blush)]":"hairline bg-white"}`}>{p}</button>)}</div>}<label className="mt-7 grid gap-3"><span className="display text-2xl font-semibold text-[var(--wine)]">{mode==="guided"?prompt:"Ce vrei să lași aici?"}</span><textarea value={body} onChange={e=>setBody(e.target.value)} className="min-h-56 resize-y rounded-2xl border hairline bg-white/70 p-5 leading-8 outline-none focus:border-[var(--rose)]" placeholder="Poți începe cu o singură propoziție…"/></label><div className="mt-5 flex justify-end"><button onClick={save} className="button-primary"><Plus size={17}/>Păstrează în jurnal</button></div></section><section><label className="relative block"><Search className="absolute left-4 top-3.5 text-[var(--muted)]" size={18}/><input aria-label="Caută în jurnal" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Caută după cuvinte sau dată…" className="min-h-12 w-full rounded-xl border hairline bg-white pl-11 pr-4 outline-none focus:border-[var(--rose)]"/></label><div className="mt-4 grid gap-3">{filtered.length===0?<Empty title="Încă nu este nimic aici." copy="Prima propoziție poate fi suficientă."/>:filtered.map(e=><article key={e.id} className="editorial-card p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-[var(--rose-dark)]">{new Intl.DateTimeFormat("ro-RO",{dateStyle:"long"}).format(new Date(e.entry_date))}</p>{e.title&&<h2 className="display mt-2 text-2xl font-semibold text-[var(--wine)]">{e.title}</h2>}</div><div className="flex"><button aria-label="Favoritează" onClick={()=>favorite(e)} className="grid size-10 place-items-center"><Heart size={17} className={e.is_favorite?"fill-[var(--rose)] text-[var(--rose)]":""}/></button><button aria-label="Șterge" onClick={()=>remove(e.id)} className="grid size-10 place-items-center"><Trash2 size={17}/></button></div></div><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-[var(--muted)]">{e.body}</p></article>)}</div></section></ToolLayout>}
