"use client";
/* eslint-disable react-hooks/immutability */
import { BarChart3, BookOpen, CheckCircle2, Clock3 } from "lucide-react";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { ToolLayout } from "./planner";
type Stats={checkins:number;energy:number;focus:number;minutes:number;tasks:number;journal:number};
export function Patterns(){const [stats,setStats]=useState<Stats>({checkins:0,energy:0,focus:0,minutes:0,tasks:0,journal:0});useEffect(()=>{void load()},[]);async function load(){const s=createClient();if(!s){const fs=JSON.parse(localStorage.getItem("starea-mea-focus")||"[]");const ts=JSON.parse(localStorage.getItem("starea-mea-tasks")||"[]");const js=JSON.parse(localStorage.getItem("starea-mea-journal")||"[]");setStats(x=>({...x,minutes:fs.reduce((a:number,b:{completed_minutes:number})=>a+b.completed_minutes,0),tasks:ts.filter((t:{status:string})=>t.status==="done").length,journal:js.length}));return}const [{data:checkins},{data:focus},{count:tasks},{count:journal}]=await Promise.all([s.from("daily_checkins").select("energy,focus"),s.from("focus_sessions").select("completed_minutes"),s.from("tasks").select("*",{count:"exact",head:true}).eq("status","done"),s.from("journal_entries").select("*",{count:"exact",head:true})]);const c=checkins||[];setStats({checkins:c.length,energy:c.length?c.reduce((a,x)=>a+x.energy,0)/c.length:0,focus:c.length?c.reduce((a,x)=>a+(x.focus||0),0)/c.length:0,minutes:(focus||[]).reduce((a,x)=>a+x.completed_minutes,0),tasks:tasks||0,journal:journal||0})}
 const cards=[[BarChart3,"Check-in-uri",stats.checkins],[Clock3,"Minute de focus",stats.minutes],[CheckCircle2,"Taskuri finalizate",stats.tasks],[BookOpen,"Intrări în jurnal",stats.journal]] as const;return <ToolLayout eyebrow="Tiparele mele" title="Lucrurile mici pe care le-ai făcut." intro="Fără streak-uri pierdute și fără interpretări medicale. Doar datele tale, privite cu blândețe."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([Icon,label,value])=><article key={label} className="editorial-card p-6"><Icon className="text-[var(--rose)]"/><p className="display mt-5 text-5xl font-semibold text-[var(--wine)]">{value}</p><p className="mt-2 text-sm text-[var(--muted)]">{label}</p></article>)}</div><section className="editorial-card p-7"><h2 className="display text-3xl font-semibold text-[var(--wine)]">Ce putem observa</h2>{stats.checkins<7?<p className="mt-3 text-sm leading-7 text-[var(--muted)]">După cel puțin 7 check-in-uri vom afișa tendințe descriptive. Nu vom sugera cauzalitate și nu vom infera diagnostice.</p>:<p className="mt-3 text-sm leading-7 text-[var(--muted)]">În zilele în care ai raportat starea ta, energia medie a fost {stats.energy.toFixed(1)} din 5, iar focusul mediu {stats.focus.toFixed(1)} din 5.</p>}</section></ToolLayout>}
