"use client";
/* eslint-disable react-hooks/immutability */
import { Check, ChevronDown, Circle, Clock3, Plus, RotateCcw, Trash2, Zap } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Task={id:string;title:string;estimated_minutes:number;energy:"low"|"medium"|"high";category:string;priority:number;status:"todo"|"doing"|"done"|"reschedule";due_date:string|null};
const demoKey="starea-mea-tasks";
export function Planner(){
 const [tasks,setTasks]=useState<Task[]>([]);const [title,setTitle]=useState("");const [duration,setDuration]=useState(15);const [energy,setEnergy]=useState<Task["energy"]>("medium");const [category,setCategory]=useState("personal");const [view,setView]=useState<"today"|"week"|"later">("today");const [capacity,setCapacity]=useState(60);const [loading,setLoading]=useState(true);
 useEffect(()=>{void load();},[]);
 async function load(){const supabase=createClient();if(supabase){const {data:{user}}=await supabase.auth.getUser();if(user){const {data}=await supabase.from("tasks").select("id,title,estimated_minutes,energy,category,priority,status,due_date").order("sort_order");setTasks((data as Task[])||[]);setLoading(false);return;}}setTasks(JSON.parse(localStorage.getItem(demoKey)||"[]"));setLoading(false);}
 function persist(next:Task[]){setTasks(next);if(!createClient())localStorage.setItem(demoKey,JSON.stringify(next));}
 async function add(){if(!title.trim())return;const draft={title:title.trim(),estimated_minutes:duration,energy,category,priority:2,status:"todo" as const,due_date:view==="today"?new Date().toISOString().slice(0,10):null};const supabase=createClient();if(supabase){const {data:{user}}=await supabase.auth.getUser();if(user){const {data}=await supabase.from("tasks").insert({...draft,user_id:user.id}).select().single();if(data)persist([...tasks,data as Task]);}}else persist([...tasks,{...draft,id:crypto.randomUUID()}]);setTitle("");}
 async function update(task:Task,changes:Partial<Task>){const next=tasks.map(x=>x.id===task.id?{...x,...changes}:x);persist(next);const supabase=createClient();if(supabase)await supabase.from("tasks").update({...changes,updated_at:new Date().toISOString()}).eq("id",task.id);}
 async function remove(id:string){persist(tasks.filter(x=>x.id!==id));const supabase=createClient();if(supabase)await supabase.from("tasks").delete().eq("id",id);}
 const filtered=useMemo(()=>tasks.filter(t=>view==="later"?!t.due_date:view==="today"?t.due_date===new Date().toISOString().slice(0,10):true),[tasks,view]);const recommended=capacity<=20?1:capacity<=40?2:capacity<=60?3:5;
 return <ToolLayout eyebrow="Plan blând" title="Ce poți astăzi?" intro={`La ${capacity}% energie îți recomandăm maximum ${recommended} ${recommended===1?"lucru important":"lucruri importante"}.`}>
  <section className="editorial-card p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-bold text-[var(--wine)]">Energia disponibilă</p><p className="mt-1 text-xs text-[var(--muted)]">Planul se adaptează zilei, nu invers.</p></div><div className="flex gap-1">{[20,40,60,80,100].map(n=><button key={n} onClick={()=>setCapacity(n)} className={`min-h-10 rounded-full px-3 text-xs font-bold ${capacity===n?"bg-[var(--rose)] text-white":"bg-[var(--blush)] text-[var(--wine)]"}`}>{n}%</button>)}</div></div></section>
  <section className="editorial-card p-5 sm:p-7"><div className="grid gap-3 md:grid-cols-[1fr_auto_auto_auto_auto]"><input aria-label="Titlul taskului" value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>e.key==="Enter"&&add()} placeholder="Adaugă un lucru mic și clar…" className="min-h-12 rounded-xl border hairline bg-white px-4 outline-none focus:border-[var(--rose)]"/><Select value={duration} onChange={v=>setDuration(Number(v))} label="Durată" options={[[5,"5 min"],[10,"10 min"],[15,"15 min"],[25,"25 min"],[45,"45 min"],[60,"60+ min"]]}/><Select value={energy} onChange={v=>setEnergy(v as Task["energy"])} label="Energie" options={[["low","joasă"],["medium","medie"],["high","ridicată"]]}/><Select value={category} onChange={setCategory} label="Categorie" options={[["personal","personal"],["munca","muncă"],["casa","casă"],["grija","grijă de mine"]]}/><button onClick={add} className="button-primary"><Plus size={17}/>Adaugă</button></div></section>
  <div className="flex gap-2">{[["today","Astăzi"],["week","Săptămâna aceasta"],["later","Mai târziu"]].map(([id,label])=><button key={id} onClick={()=>setView(id as typeof view)} className={`min-h-11 rounded-full px-4 text-sm font-bold ${view===id?"bg-[var(--wine)] text-white":"bg-white text-[var(--muted)]"}`}>{label}</button>)}</div>
  <section className="grid gap-3">{loading?<TaskSkeleton/>:filtered.length===0?<Empty title="Planul are loc să respire." copy="Adaugă un singur lucru când ești pregătită."/>:filtered.map((task,index)=><article key={task.id} className={`editorial-card flex items-center gap-4 p-4 ${task.status==="done"?"opacity-55":""}`}><button aria-label={task.status==="done"?"Marchează ca nefăcut":"Marchează ca finalizat"} onClick={()=>update(task,{status:task.status==="done"?"todo":"done",completed_at:undefined} as Partial<Task>)} className={`grid size-10 shrink-0 place-items-center rounded-full border ${task.status==="done"?"border-[var(--rose)] bg-[var(--rose)] text-white":"hairline bg-white"}`}>{task.status==="done"?<Check size={18}/>:<Circle size={18}/>}</button><div className="min-w-0 flex-1"><h3 className={`font-bold text-[var(--wine)] ${task.status==="done"?"line-through":""}`}>{task.title}</h3><div className="mt-1 flex flex-wrap gap-3 text-xs text-[var(--muted)]"><span className="flex items-center gap-1"><Clock3 size={13}/>{task.estimated_minutes} min</span><span className="flex items-center gap-1"><Zap size={13}/>energie {task.energy==="low"?"joasă":task.energy==="medium"?"medie":"ridicată"}</span><span>{task.category}</span>{index>=recommended&&view==="today"&&<span className="text-[var(--rose-dark)]">poate aștepta</span>}</div></div><button title="Reprogramează" onClick={()=>update(task,{status:"reschedule",due_date:null})} className="grid size-10 place-items-center rounded-full hover:bg-[var(--blush)]"><RotateCcw size={17}/></button><button title="Șterge" onClick={()=>remove(task.id)} className="grid size-10 place-items-center rounded-full hover:bg-[var(--blush)]"><Trash2 size={17}/></button></article>)}</section>
 </ToolLayout>;
}
function Select({value,onChange,label,options}:{value:string|number;onChange:(v:string)=>void;label:string;options:(string|number)[][]}){return <label className="relative"><span className="sr-only">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="min-h-12 appearance-none rounded-xl border hairline bg-white px-4 pr-9 text-sm font-semibold"><>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</></select><ChevronDown className="pointer-events-none absolute right-3 top-4" size={15}/></label>}
export function ToolLayout({eyebrow,title,intro,children}:{eyebrow:string;title:string;intro:string;children:React.ReactNode}){return <main className="container-shell py-10 sm:py-14"><p className="eyebrow">{eyebrow}</p><div className="mt-3 grid items-end gap-4 md:grid-cols-[1fr_.7fr]"><h1 className="display text-5xl font-semibold leading-none text-[var(--wine)] sm:text-7xl">{title}</h1><p className="max-w-xl leading-7 text-[var(--muted)]">{intro}</p></div><div className="mt-10 grid gap-5">{children}</div></main>}
export function Empty({title,copy}:{title:string;copy:string}){return <div className="editorial-card grid min-h-48 place-items-center p-8 text-center"><div><p className="display text-3xl font-semibold text-[var(--wine)]">{title}</p><p className="mt-2 text-sm text-[var(--muted)]">{copy}</p></div></div>}
function TaskSkeleton(){return <div className="editorial-card h-24 animate-pulse bg-white"/>}
