"use client";
import { Download, LogOut, ShieldCheck, Trash2 } from "lucide-react";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { ToolLayout } from "./planner";
const privateTables=["profiles","user_preferences","wellbeing_consents","daily_checkins","tasks","task_steps","brain_dump_items","focus_sessions","journal_entries","calm_sessions","program_progress","subscriptions","purchases","entitlements"];
export function Profile(){const [busy,setBusy]=useState(false);const [confirming,setConfirming]=useState(false);const router=useRouter();
 async function signOut(){const s=createClient();await s?.auth.signOut();router.push("/");router.refresh()}
 async function exportData(){setBusy(true);const s=createClient();if(!s){const data={tasks:JSON.parse(localStorage.getItem("starea-mea-tasks")||"[]"),journal:JSON.parse(localStorage.getItem("starea-mea-journal")||"[]"),brain_dump:JSON.parse(localStorage.getItem("starea-mea-brain-dump")||"[]"),focus:JSON.parse(localStorage.getItem("starea-mea-focus")||"[]")};download(data)}else{const result:Record<string,unknown>={};for(const table of privateTables){const {data}=await s.from(table).select("*");result[table]=data||[]}download(result)}setBusy(false)}
 function download(data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`starea-mea-export-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}
 async function deleteAccount(){setBusy(true);const response=await fetch("/api/account",{method:"DELETE"});if(response.ok){router.push("/");router.refresh()}else setBusy(false)}
 return <ToolLayout eyebrow="Spațiul meu" title="Tu deții controlul." intro="Preferințe, consimțăminte și datele tale — într-un singur loc."><section className="grid gap-4 md:grid-cols-2"><article className="editorial-card p-7"><ShieldCheck className="text-[var(--rose)]"/><h2 className="display mt-5 text-3xl font-semibold text-[var(--wine)]">Confidențialitate</h2><p className="mt-3 text-sm leading-7 text-[var(--muted)]">Jurnalul, taskurile și check-in-urile nu sunt trimise către instrumente publicitare. Consimțământul de wellbeing este separat de marketing.</p></article><article className="editorial-card p-7"><Download className="text-[var(--rose)]"/><h2 className="display mt-5 text-3xl font-semibold text-[var(--wine)]">Exportă datele</h2><p className="mt-3 text-sm leading-7 text-[var(--muted)]">Primești un fișier JSON cu datele personale asociate contului.</p><button onClick={exportData} disabled={busy} className="button-secondary mt-6">{busy?"Se pregătește…":"Descarcă exportul"}</button></article></section><section className="editorial-card p-7"><h2 className="font-bold text-[var(--wine)]">Cont și abonament</h2><div className="mt-5 flex flex-wrap gap-3"><button onClick={async()=>{const r=await fetch("/api/stripe/portal",{method:"POST"});const d=await r.json();if(d.url)location.assign(d.url)}} className="button-secondary">Administrează Plus</button><button onClick={signOut} className="button-secondary"><LogOut size={17}/>Ieși din cont</button></div></section><section className="rounded-[18px] border border-[rgba(183,86,104,.3)] bg-white p-7"><h2 className="font-bold text-[var(--rose-dark)]">Ștergerea contului</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Această acțiune șterge definitiv contul și toate datele private. Nu poate fi anulată.</p>{!confirming?<button onClick={()=>setConfirming(true)} className="button-secondary mt-5"><Trash2 size={17}/>Începe ștergerea</button>:<div className="mt-5 rounded-xl bg-[var(--blush)] p-5"><p className="text-sm font-bold text-[var(--wine)]">Confirmi ștergerea definitivă?</p><div className="mt-4 flex gap-3"><button disabled={busy} onClick={deleteAccount} className="button-primary">{busy?"Se șterge…":"Da, șterge definitiv"}</button><button onClick={()=>setConfirming(false)} className="button-secondary">Renunță</button></div></div>}</section></ToolLayout>}
